name: Upload package to PyPI
on:
  push:
    tags:
      - "v*"

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Extract tag version
      id: tag
      run: echo "::set-output name=version::$(echo ${{ github.ref }} | sed -e 's/refs\/tags\/v//')"
    - name: Build
      run: |
        sh package_python.sh ${{ steps.tag.outputs.version }}
    - name: Upload to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
      run: |
        cd build/python/${{ steps.tag.outputs.version }}/core && python -m twine upload dist/*
        cd ../small && python -m twine upload dist/*
        cd ../full && python -m twine upload dist/*
