on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_dic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto
          cache: gradle
      - name: Check dictionary compilation
        run:
          ./gradlew --info build